[workspace]
resolver = "2"
members = ["bin/api"]

[workspace.dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
axum = { version = "0.8.8", features = ["macros"] }
bincode = "1"

bson = { version = "3.1", features = ["serde", "chrono-0_4", "serde_with-3"] }
calamine = "0.24"
candle-core = "0.9"
candle-nn = "0.9"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.9"

clap = { version = "4", features = ["derive"] }
futures = "0.3"
google-cloud-storage = { version = "0.20", features = ["default"] }

linfa = "0.8.1"
linfa-linear = "0.8.1"
linfa-ensemble = "0.8.1"
linfa-trees = "0.8.1"

mongodb = { version = "3.5.1", features = ["bson-3"] }
ndarray = "0.16"
serde_with = { version = "3.0", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.148"

rand = "0.8"
rayon = "1.11"

reqwest = { version = "0.12.28", features = ["json", "stream", "multipart"]}
rust_decimal = { version = "1.35", features = ["serde"] }
rust_decimal_macros = "1.40.0"

ta = "0.5"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tower-http = {version = "0.6.8", features = ["cors"]}
tracing = {version = "0.1.40"}
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }


# Point to the relative path on your machine
#rustic-agent = { path = "../rustic-ai-backend-rs/crates/rustic-agent" }
#rustic-boot = { path = "../rustic-ai-backend-rs/crates/rustic-boot" }
#rustic-core = { path = "../rustic-ai-backend-rs/crates/rustic-core" }
#rustic-ml = { path = "../rustic-ai-backend-rs/crates/rustic-ml" }
#rustic-storage = { path = "../rustic-ai-backend-rs/crates/rustic-storage" }

rustic-agent = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-agent"}
rustic-boot = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-boot"}
rustic-core = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-core"}
rustic-ml = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-ml"}
rustic-storage = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-storage"}
rustic-finance = { git = "https://github.com/rkapps/rustic-backend", package = "rustic-finance"}
