[package]
name = "fin-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace= true
bson.workspace=true
chrono.workspace=true
mongodb.workspace=true
rust_decimal.workspace=true
rust_decimal_macros.workspace=true
serde.workspace = true
serde_with.workspace=true
storage-core.workspace = true
tracing.workspace=true

fin-providers.workspace = true
